### PR TITLE
fix(Checkbox): center checkbox icon

### LINKED ISSUE #1819: [bug]: Icons are not centered in the checkboxes
### What version of design-system are you using?

Browser: Arc

### What's Wrong?

Icons are not centered in the checkboxes, it's very visible in the intermediate state.

CleanShot 2024-11-12 at 12 21 53@2x

### To Reproduce

Find any checkbox (ex: in the edit view table).

### Expected Behaviour

Icons should be centered.

### PR DESCRIPTION
**Pull request by PlanckConst**
### What was changed?

Added justify-content: center and align-items: center to the parent container named CheckboxIndicator located in 
packages\design-system\src\components\Checkbox\Checkbox.tsx

### Why is it needed?

Checkbox Icon was not centered within parent container

### How to test it?

You can test this feature by running the application and attempting the checkbox module.

### Related issue(s)/PR(s)

Related Issue:  [https://github.com/strapi/design-system/issues/1819](https://github.com/strapi/design-system/issues/1819)
fixes #1819

### CODE REVIEW

**Comment by hanpaine** [comment]
hey @PlanckConst thanks for the contribution! We'll take a look soon 🙏

**Comment by lucasboilly** [comment]
Hey @PlanckConst! Thanks, it looks much better :)

I just added @remidej for the code review.

**Comment by PlanckConst** [comment]
Glad I could help! My first open source contribution~

**Comment by lucasboilly** [comment]
@PlanckConst congrats! 😄

File: packages/design-system/src/components/Checkbox/Checkbox.tsx [hunk 1]
```diff
@@ -52,7 +52,7 @@ const CheckboxEl = React.forwardRef<CheckboxElement, CheckboxElProps>(
 
     return (
       <CheckboxRoot ref={composedRefs} checked={checked} onCheckedChange={setChecked} {...props}>
-        <CheckboxIndicator style={{ display: 'inline-flex', pointerEvents: 'auto' }} forceMount>
+        <CheckboxIndicator style={{ display: 'inline-flex', pointerEvents: 'auto', justifyContent: 'center', alignItems: 'center' }} forceMount>
```
Comment (markkaylor) [inline packages/design-system/src/components/Checkbox/Checkbox.tsx:55]: Confused why we are applying all the styles here inline. Couldn't we apply them to the CheckBoxIndicator styled component on line 103?

Comment (chitangchin) [reply packages/design-system/src/components/Checkbox/Checkbox.tsx:55]: Hey Mark,

This is my other git acc, yes you are right I must have overlooked the styled component below.

Comment (chitangchin) [reply packages/design-system/src/components/Checkbox/Checkbox.tsx:55]: Are you making the change or do you want me to repush the changes?

Comment (markkaylor) [reply packages/design-system/src/components/Checkbox/Checkbox.tsx:55]: No worries! If you can make the changes and push that would be great!

You will also need to add a [changeset](https://github.com/strapi/design-system/pull/1821#issuecomment-2477400451). You can find out how to do it here in the [contributing docs](https://github.com/strapi/design-system/blob/main/CONTRIBUTING.md#pull-requests)

Comment (chitangchin) [reply packages/design-system/src/components/Checkbox/Checkbox.tsx]: Hey Mark I've updated the inline style and added it to the style component.
Also added the changelog

File: packages/design-system/src/components/Checkbox/Checkbox.tsx [hunk 2]
```diff
@@ -52,7 +52,7 @@ const CheckboxEl = React.forwardRef<CheckboxElement, CheckboxElProps>(
 
     return (
       <CheckboxRoot ref={composedRefs} checked={checked} onCheckedChange={setChecked} {...props}>
-        <CheckboxIndicator style={{ display: 'inline-flex', pointerEvents: 'auto' }} forceMount>
+        <CheckboxIndicator style={{ display: 'inline-flex', pointerEvents: 'auto'}} forceMount>
```
Comment (markkaylor) [inline packages/design-system/src/components/Checkbox/Checkbox.tsx:55]: Sorry maybe my previous comment wasn't clear. Could we add these to the styled component as well so all styles are applied in the same place and we can get rid of the style tag here?

Comment (chitangchin) [reply packages/design-system/src/components/Checkbox/Checkbox.tsx:55]: I see now, i agree it is redundant. Ill make that change.

Thanks for clarifying!

File: .changeset/purple-rivers-divide.md [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+
+Refactored inline styling and added it to checkbox indicator stype component
+
+Original:
+
+      <CheckboxIndicator style={{ display: 'inline-flex', pointerEvents: 'auto'}} forceMount>
+
+Updated:
+
+      <CheckboxIndicator forceMount>
```
Comment (markkaylor) [inline .changeset/purple-rivers-divide.md]: Just for future reference I think the first line that describes what you did is enough. I think most of the time it can probably be the same as your commit.  This is fine too, thanks for the detail :)

```suggestion

```

File: packages/design-system/src/components/Checkbox/Checkbox.tsx (hunk 2 above)
Comment (markkaylor) [reply packages/design-system/src/components/Checkbox/Checkbox.tsx]: Great thanks!

**Review by markkaylor — APPROVED** [review]
Nice, looks good. I think we can merge once the tests pass

File: .changeset/purple-rivers-divide.md (hunk 3 above)
Comment (chitangchin) [reply .changeset/purple-rivers-divide.md]: Thanks Mark!

**Review by markkaylor — APPROVED** [review]

**Comment by chitangchin** [comment]
Do i have to do anything to resolve the chromatic pull request?

**Comment by markkaylor** [comment]
> Do i have to resolve the chromatic test?

No need to worry about the chromatic test that was failing, for some reason I couldn't merge the PR last night but I'll get it merged at some point today. Thanks for the contribution.
